from cortexheal.learning.trust import TrustEngine
from cortexheal.storage.postgres import get_connection

with get_connection() as conn:
    with conn.cursor() as cur:
        # Get real pattern generated by demo scripts (fingerprint length is 64 + 3 = 67 chars)
        cur.execute("SELECT pattern_id, fingerprint, occurrences FROM pattern_records WHERE LENGTH(fingerprint) > 60 ORDER BY created_at DESC LIMIT 1")
        row = cur.fetchone()
        
print(f"Pattern ID: {row[0]}")
print(f"Fingerprint: {row[1]}")
print(f"Occurrences: {row[2]}")

engine = TrustEngine()
evidence = engine.calculate_trust(row[0])
for action, stats in evidence.actions.items():
    print(f"Action: {action} | Attempts: {stats.attempted} | Success: {stats.verified_success} | Fail: {stats.verified_failure} | Rate: {stats.success_rate:.2f} | Trust: {stats.trust_score:.2f} | Risk: {stats.risk_level}")

