"""
CortexHeal CLI -- pip-installable command-line interface.

Commands:
    cortexheal init    -- Set up environment, database, and first API key.
    cortexheal start   -- Start the backend server.
    cortexheal demo    -- Run a live stuck-loop + budget-overrun demo.
    cortexheal status  -- Health check against the running instance.
    cortexheal debug   -- Inspect a specific run's events (legacy utility).

Uses Click. Console entry point: cortexheal = cortexheal.cli.main:cli
"""

import os
import sys
import time
import shutil
import subprocess
import secrets
import textwrap

import click

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

ENV_TEMPLATE = textwrap.dedent("""\
    # CortexHeal Environment -- auto-generated by `cortexheal init`
    DATABASE_URL=postgresql://cortexheal:cortexpassword@localhost:5433/cortexheal_db
    DB_POOL_SIZE=5
    DB_MAX_OVERFLOW=10
    DB_TIMEOUT=30
    CORTEXHEAL_HOST=0.0.0.0
    CORTEXHEAL_PORT=8000
    CORTEXHEAL_WORKERS=4
    ENVIRONMENT=development
    ADMIN_TOKENS=dev-admin-key
    OPERATOR_TOKENS=dev-operator-key
    VIEWER_TOKENS=dev-viewer-key
    ALLOW_DEV_TOKENS=True
    ENABLE_TELEMETRY=True
    MAX_QUEUE_SIZE=10000
    BATCH_SIZE=100
    FLUSH_INTERVAL_MS=500
    DETECTOR_VERSION=1.0
    POLICY_VERSION=1.0
    API_RATE_LIMIT_PER_MIN=60
""")


def _find_docker_compose_file():
    """Locate docker-compose.yml relative to the installed package."""
    candidates = [
        os.path.join(os.getcwd(), "docker-compose.yml"),
        os.path.join(PROJECT_ROOT, "docker-compose.yml"),
    ]
    for path in candidates:
        if os.path.isfile(path):
            return path
    return None


def _docker_available():
    """Check whether docker CLI is reachable."""
    try:
        r = subprocess.run(
            ["docker", "info"],
            capture_output=True, timeout=10,
        )
        return r.returncode == 0
    except Exception:
        return False


def _wait_for_postgres(database_url, timeout=30):
    """Block until PostgreSQL accepts connections or timeout."""
    import psycopg2
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            conn = psycopg2.connect(database_url)
            conn.close()
            return True
        except Exception:
            time.sleep(1)
    return False


def _server_healthy(port=8000):
    """Quick GET /health check against the running server."""
    import urllib.request
    try:
        url = "http://127.0.0.1:{}/health".format(port)
        req = urllib.request.Request(url, method="GET")
        with urllib.request.urlopen(req, timeout=3) as resp:
            return resp.status == 200
    except Exception:
        return False


# ---------------------------------------------------------------------------
# CLI Group
# ---------------------------------------------------------------------------

@click.group()
@click.version_option(package_name="cortexheal")
def cli():
    """CortexHeal -- Deterministic safety & circuit-breaker control plane for AI agents."""
    pass


# ---------------------------------------------------------------------------
# cortexheal init
# ---------------------------------------------------------------------------

@cli.command()
@click.option("--skip-docker", is_flag=True, help="Skip Docker/Postgres startup (use existing database).")
@click.option("--db-url", default=None, help="Override DATABASE_URL instead of using the default.")
def init(skip_docker, db_url):
    """Set up environment, start Postgres, run migrations, create first API key."""

    click.secho("\n  =================================================", fg="cyan")
    click.secho("       CortexHeal -- First-Time Setup              ", fg="cyan")
    click.secho("  =================================================\n", fg="cyan")

    # --- 1. Create .env -----------------------------------------------------------
    env_path = os.path.join(os.getcwd(), ".env")
    if os.path.isfile(env_path):
        click.secho("  [OK] .env already exists -- skipping creation.", fg="yellow")
    else:
        contents = ENV_TEMPLATE
        if db_url:
            contents = contents.replace(
                "DATABASE_URL=postgresql://cortexheal:cortexpassword@localhost:5433/cortexheal_db",
                "DATABASE_URL={}".format(db_url),
            )
        with open(env_path, "w") as f:
            f.write(contents)
        click.secho("  [OK] Created .env with default configuration.", fg="green")

    # Reload settings from the newly-created .env
    os.environ.setdefault("DATABASE_URL", db_url or "postgresql://cortexheal:cortexpassword@localhost:5433/cortexheal_db")

    database_url = db_url or os.environ.get(
        "DATABASE_URL",
        "postgresql://cortexheal:cortexpassword@localhost:5433/cortexheal_db",
    )

    # --- 2. Start Postgres via Docker Compose -------------------------------------
    if not skip_docker:
        compose_file = _find_docker_compose_file()
        if compose_file and _docker_available():
            click.echo("  -> Starting PostgreSQL via Docker Compose...")
            compose_dir = os.path.dirname(compose_file)
            result = subprocess.run(
                ["docker", "compose", "up", "-d"],
                cwd=compose_dir,
                capture_output=True, text=True, timeout=60,
            )
            if result.returncode == 0:
                click.secho("  [OK] PostgreSQL container started.", fg="green")
            else:
                click.secho("  [FAIL] Docker Compose failed: {}".format(result.stderr.strip()), fg="red")
                click.echo("    You can start Postgres manually and re-run with --skip-docker.")
                raise SystemExit(1)
        elif not _docker_available():
            click.secho("  [WARN] Docker not found -- skipping container start.", fg="yellow")
            click.echo("    Ensure PostgreSQL is running and DATABASE_URL is correct in .env.")
        else:
            click.secho("  [WARN] docker-compose.yml not found -- skipping container start.", fg="yellow")
    else:
        click.secho("  -> Skipping Docker startup (--skip-docker).", fg="yellow")

    # --- 3. Wait for Postgres -----------------------------------------------------
    click.echo("  -> Waiting for PostgreSQL to accept connections...")
    if _wait_for_postgres(database_url, timeout=30):
        click.secho("  [OK] PostgreSQL is ready.", fg="green")
    else:
        click.secho("  [FAIL] Could not connect to PostgreSQL within 30s.", fg="red")
        click.echo("    DATABASE_URL: {}".format(database_url))
        raise SystemExit(1)

    # --- 4. Initialize schema (init_db) -------------------------------------------
    click.echo("  -> Creating database schema...")
    # Ensure the settings module picks up our DATABASE_URL
    os.environ["DATABASE_URL"] = database_url
    from cortexheal.storage.postgres import init_db
    init_db()
    click.secho("  [OK] Database schema initialized.", fg="green")

    # --- 5. Generate first ADMIN API key ------------------------------------------
    click.echo("  -> Generating your first ADMIN API key...")
    from cortexheal.models.auth import ApiKey, hash_key, generate_raw_key
    from cortexheal.storage.postgres import save_api_key

    raw_key = generate_raw_key("ADMIN")
    k_hash = hash_key(raw_key)
    prefix = raw_key[:16] + "..."
    api_key = ApiKey(
        key_hash=k_hash,
        key_prefix=prefix,
        name="CLI-generated Admin Key",
        org_id="default_org",
        role="ADMIN",
    )
    save_api_key(api_key)

    click.echo()
    click.secho("  +-------------------------------------------------------------------+", fg="green")
    click.secho("  |  Your ADMIN API Key (shown once -- save it now):                   |", fg="green")
    click.secho("  |  {}  |".format(raw_key.ljust(60)), fg="green", bold=True)
    click.secho("  +-------------------------------------------------------------------+", fg="green")
    click.echo()

    # --- 6. Summary ---------------------------------------------------------------
    port = int(os.environ.get("CORTEXHEAL_PORT", "8000"))
    click.secho("  Setup complete. Next steps:", fg="cyan")
    click.echo("    1. Start the server:      cortexheal start")
    click.echo("    2. Run a live demo:        cortexheal demo")
    click.echo("    3. Open the dashboard:     http://localhost:{}".format(port))
    click.echo("    4. Open the API docs:      http://localhost:{}/docs".format(port))
    click.echo("    5. Log in with your key:   {}...".format(raw_key[:20]))
    click.echo()


# ---------------------------------------------------------------------------
# cortexheal start
# ---------------------------------------------------------------------------

@cli.command()
@click.option("--port", default=8000, type=int, help="Port to run the server on.")
@click.option("--host", default="0.0.0.0", help="Host to bind to.")
@click.option("--reload", "use_reload", is_flag=True, help="Enable auto-reload for development.")
@click.option("--workers", default=1, type=int, help="Number of Uvicorn workers.")
def start(port, host, use_reload, workers):
    """Start the CortexHeal backend server."""

    click.secho("\n  Starting CortexHeal server on http://{}:{} ...\n".format(host, port), fg="cyan")

    import uvicorn
    uvicorn.run(
        "cortexheal.server.api:app",
        host=host,
        port=port,
        reload=use_reload,
        workers=workers,
        log_level="info",
    )


# ---------------------------------------------------------------------------
# cortexheal demo
# ---------------------------------------------------------------------------

@cli.command()
@click.option("--port", default=8000, type=int, help="Port of the running CortexHeal server.")
@click.option("--skip-server-check", is_flag=True, help="Skip the health check before running.")
def demo(port, skip_server_check):
    """Run a live stuck-loop + budget-overrun demo against the running instance.

    Reuses existing example scripts so a first-time user sees real incidents
    appear in the dashboard within seconds.
    """

    click.secho("\n  =================================================", fg="cyan")
    click.secho("       CortexHeal -- Live Demo                     ", fg="cyan")
    click.secho("  =================================================\n", fg="cyan")

    # --- 1. Check server health ---------------------------------------------------
    if not skip_server_check:
        click.echo("  -> Checking server health...")
        if _server_healthy(port):
            click.secho("  [OK] Server is healthy.", fg="green")
        else:
            click.secho("  [FAIL] Server not reachable on port {}.".format(port), fg="red")
            click.echo("    Start the server first:  cortexheal start")
            click.echo("    Or use --skip-server-check to bypass this check.")
            raise SystemExit(1)

    # --- 2. Run stuck-loop demo ---------------------------------------------------
    click.echo("\n  -- Scenario 1: Stuck-Loop Detection & Recovery --\n")
    try:
        from examples.demo_stuck_loop_with_recovery import main as run_stuck_loop
        run_stuck_loop()
    except ImportError:
        # When installed via pip, examples/ is not on sys.path.
        # Try adding PROJECT_ROOT to sys.path.
        sys.path.insert(0, PROJECT_ROOT)
        try:
            from examples.demo_stuck_loop_with_recovery import main as run_stuck_loop
            run_stuck_loop()
        except ImportError as e:
            click.secho("  [WARN] Could not import stuck-loop demo: {}".format(e), fg="yellow")
            click.echo("    Ensure you are running from the CortexHeal project directory,")
            click.echo("    or that 'langgraph' is installed: pip install cortexheal[langgraph]")
            # Continue to try the budget demo

    click.echo()

    # --- 3. Run budget-overrun demo -----------------------------------------------
    click.echo("  -- Scenario 2: Budget Overrun Detection --\n")
    try:
        from examples.demo_budget_overrun import main as run_budget_overrun
        run_budget_overrun()
    except ImportError:
        sys.path.insert(0, PROJECT_ROOT)
        try:
            from examples.demo_budget_overrun import main as run_budget_overrun
            run_budget_overrun()
        except ImportError as e:
            click.secho("  [WARN] Could not import budget-overrun demo: {}".format(e), fg="yellow")
            click.echo("    Ensure 'langgraph' is installed: pip install cortexheal[langgraph]")

    # --- 4. Summary ---------------------------------------------------------------
    click.echo()
    click.secho("  +-------------------------------------------------------------------+", fg="green")
    click.secho("  |  Demo complete! Open the dashboard to see live incidents:          |", fg="green")
    click.secho("  |  http://localhost:{}  |".format(str(port).ljust(50)), fg="green", bold=True)
    click.secho("  +-------------------------------------------------------------------+", fg="green")
    click.echo()


# ---------------------------------------------------------------------------
# cortexheal status
# ---------------------------------------------------------------------------

@cli.command()
@click.option("--port", default=8000, type=int, help="Port of the running CortexHeal server.")
@click.option("--json", "as_json", is_flag=True, help="Output as JSON.")
def status(port, as_json):
    """Health check against the running CortexHeal instance."""

    import urllib.request
    import json

    endpoints = {
        "health": "http://127.0.0.1:{}/health".format(port),
        "readiness": "http://127.0.0.1:{}/readiness".format(port),
    }

    results = {}
    for name, url in endpoints.items():
        try:
            req = urllib.request.Request(url, method="GET")
            with urllib.request.urlopen(req, timeout=5) as resp:
                data = json.loads(resp.read().decode())
                results[name] = data
        except Exception as e:
            results[name] = {"status": "UNREACHABLE", "error": str(e)}

    if as_json:
        click.echo(json.dumps(results, indent=2))
        return

    click.echo()
    health = results.get("health", {})
    readiness = results.get("readiness", {})

    health_status = health.get("status", "UNREACHABLE")
    readiness_status = readiness.get("status", "UNREACHABLE")

    color_map = {
        "HEALTHY": "green",
        "DEGRADED": "yellow",
        "NOT_READY": "red",
        "UNREACHABLE": "red",
    }

    click.secho("  Health:    {}".format(health_status), fg=color_map.get(health_status, "white"))
    click.secho("  Readiness: {}".format(readiness_status), fg=color_map.get(readiness_status, "white"))

    if readiness_status not in ("HEALTHY",):
        reason = readiness.get("reason", readiness.get("error", ""))
        if reason:
            click.echo("  Reason:    {}".format(reason))

    click.echo("  Server:    http://127.0.0.1:{}".format(port))
    click.echo("  Dashboard: http://127.0.0.1:{}".format(port))
    click.echo("  API Docs:  http://127.0.0.1:{}/docs".format(port))
    click.echo()

    if health_status == "UNREACHABLE":
        raise SystemExit(1)


# ---------------------------------------------------------------------------
# cortexheal mcp
# ---------------------------------------------------------------------------

@cli.command()
def mcp():
    """Start the CortexHeal Model Context Protocol (MCP) server over stdio.
    
    This is meant to be invoked by an AI assistant like Claude Desktop,
    Cursor, or Windsurf to read live incident data and context.
    """
    try:
        from cortexheal.mcp_server import main as mcp_main
        mcp_main()
    except ImportError as e:
        click.secho(f"  [FAIL] Could not import MCP server: {e}", fg="red")
        click.echo("    Ensure the 'mcp' extra is installed: pip install cortexheal[mcp]")
        raise SystemExit(1)

# ---------------------------------------------------------------------------
# cortexheal debug (legacy -- delegate to existing argparse utility)
# ---------------------------------------------------------------------------

@cli.command()
@click.argument("run_id")
def debug(run_id):
    """Inspect a specific run's event timeline (legacy debug utility)."""
    from cortexheal.storage.postgres import get_run, get_events_for_run

    run = get_run(run_id)
    if not run:
        click.secho("Run {} not found.".format(run_id), fg="red")
        raise SystemExit(1)

    click.echo("RUN {} | Agent: {} | Status: {}".format(run.run_id, run.agent_id, run.status))
    click.echo("Start: {} | End: {}".format(run.start_time, run.end_time))
    click.echo("-" * 50)

    events = get_events_for_run(run_id)
    for event in events:
        tokens_info = " | Tokens: {}".format(event.tokens.total) if event.tokens and event.tokens.total > 0 else ""
        latency_info = " | {}ms".format(event.latency_ms) if event.latency_ms else ""
        tool_info = " {}".format(event.tool) if event.tool else ""
        click.echo("{} {}{}[{}]{}{}".format(
            event.sequence_number, event.event_type, tool_info, event.status, latency_info, tokens_info
        ))


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    cli()
